export const SET_LOADING_STATUS = "SET_LOADING_STATUS";
export const SET_DATA = "SET_DATA";
export const SET_USERS = "SET_USERS";
export const SET_LOADING_MORE = "SET_LOADING_MORE";
export const SET_LOGOUT = "SET_LOGOUT";
export const SET_MY_PRODUCTS = "SET_MY_PRODUCTS";
export const SET_MY_NOTIFICATION = "SET_MY_NOTIFICATION";
export const SET_CARTS = "SET_CARTS";
export const SET_CHECKOUT_DATA = "SET_CHECKOUT_DATA";
export const SET_STORE_DELIVERY_DATA = "SET_STORE_DELIVERY_DATA";
export const SET_STORE_PROMOTIONAL_DATA = "SET_STORE_PROMOTIONAL_DATA";
export const SET_STORE_PROMOTIONAL_POPUP_DATA =
  "SET_STORE_PROMOTIONAL_POPUP_DATA";
export const SWITCH_THEME = "SWITCH_THEME";
